import { db } from "@/server/db";
import { type Partner, partners } from "@/server/db/schema";
import { createId } from "@paralleldrive/cuid2";

function getRandomDate(start: Date, end: Date): Date {
  return new Date(
    start.getTime() + Math.random() * (end.getTime() - start.getTime()),
  );
}

const startDate = new Date(2024, 0, 1); // January 1, 2024
const endDate = new Date(2024, 4, 31); // May 31, 2024

const partnersSeed: Partner[] = [
  {
    id: createId(),
    name: "Tech Innovations Ltd.",
    status: "Verified",
    orgType: "Corporate",
    createdAt: getRandomDate(startDate, endDate),
    updatedAt: getRandomDate(startDate, endDate),
    lastInteraction: getRandomDate(startDate, endDate),
    availableResources: "Technology consultancy, software development",
  },
  {
    id: createId(),
    name: "Green Energy Solutions",
    status: "Pending",
    orgType: "Limited Liability Company (LLC)",
    createdAt: getRandomDate(startDate, endDate),
    updatedAt: getRandomDate(startDate, endDate),
    lastInteraction: getRandomDate(startDate, endDate),
    availableResources: "Renewable energy projects, environmental consultancy",
  },
  {
    id: createId(),
    name: "HealthFirst Medical",
    status: "Verified",
    orgType: "Partnership",
    createdAt: getRandomDate(startDate, endDate),
    updatedAt: getRandomDate(startDate, endDate),
    lastInteraction: getRandomDate(startDate, endDate),
    availableResources: "Healthcare services, medical supplies",
  },
  {
    id: createId(),
    name: "EduTech Innovations",
    status: "Unverified",
    orgType: "Educational",
    createdAt: getRandomDate(startDate, endDate),
    updatedAt: getRandomDate(startDate, endDate),
    lastInteraction: getRandomDate(startDate, endDate),
    availableResources: "Educational software, e-learning platforms",
  },
  {
    id: createId(),
    name: "BrightFuture NPO",
    status: "Verified",
    orgType: "NPO",
    createdAt: getRandomDate(startDate, endDate),
    updatedAt: getRandomDate(startDate, endDate),
    lastInteraction: getRandomDate(startDate, endDate),
    availableResources: "Community development, social services",
  },
  {
    id: createId(),
    name: "Urban Development Co.",
    status: "Pending",
    orgType: "Corporate",
    createdAt: getRandomDate(startDate, endDate),
    updatedAt: getRandomDate(startDate, endDate),
    lastInteraction: getRandomDate(startDate, endDate),
    availableResources: "Urban planning, construction",
  },
  {
    id: createId(),
    name: "BlueSky Travel Agency",
    status: "Unverified",
    orgType: "Sole Proprietorship",
    createdAt: getRandomDate(startDate, endDate),
    updatedAt: getRandomDate(startDate, endDate),
    lastInteraction: getRandomDate(startDate, endDate),
    availableResources: "Travel packages, tour guides",
  },
  {
    id: createId(),
    name: "FutureTech Robotics",
    status: "Verified",
    orgType: "Corporate",
    createdAt: getRandomDate(startDate, endDate),
    updatedAt: getRandomDate(startDate, endDate),
    lastInteraction: getRandomDate(startDate, endDate),
    availableResources: "Robotics solutions, AI development",
  },
  {
    id: createId(),
    name: "GreenWorld Agriculture",
    status: "Pending",
    orgType: "Cooperative",
    createdAt: getRandomDate(startDate, endDate),
    updatedAt: getRandomDate(startDate, endDate),
    lastInteraction: getRandomDate(startDate, endDate),
    availableResources: "Sustainable farming, organic produce",
  },
  {
    id: createId(),
    name: "Global Trade Inc.",
    status: "Verified",
    orgType: "Corporate",
    createdAt: getRandomDate(startDate, endDate),
    updatedAt: getRandomDate(startDate, endDate),
    lastInteraction: getRandomDate(startDate, endDate),
    availableResources: "International trade, logistics",
  },
  {
    id: createId(),
    name: "Innovatech Solutions",
    status: "Verified",
    orgType: "Limited Liability Company (LLC)",
    createdAt: getRandomDate(startDate, endDate),
    updatedAt: getRandomDate(startDate, endDate),
    lastInteraction: getRandomDate(startDate, endDate),
    availableResources: "IT services, custom software development",
  },
  {
    id: createId(),
    name: "HealthyLife Wellness Center",
    status: "Pending",
    orgType: "Partnership",
    createdAt: getRandomDate(startDate, endDate),
    updatedAt: getRandomDate(startDate, endDate),
    lastInteraction: getRandomDate(startDate, endDate),
    availableResources: "Wellness programs, health consultancy",
  },
  {
    id: createId(),
    name: "SmartCity Innovations",
    status: "Unverified",
    orgType: "Corporate",
    createdAt: getRandomDate(startDate, endDate),
    updatedAt: getRandomDate(startDate, endDate),
    lastInteraction: getRandomDate(startDate, endDate),
    availableResources: "Smart city solutions, IoT devices",
  },
  {
    id: createId(),
    name: "EcoFriendly Solutions",
    status: "Verified",
    orgType: "Limited Liability Company (LLC)",
    createdAt: getRandomDate(startDate, endDate),
    updatedAt: getRandomDate(startDate, endDate),
    lastInteraction: getRandomDate(startDate, endDate),
    availableResources: "Environmental consultancy, sustainable products",
  },
  {
    id: createId(),
    name: "Community Builders NPO",
    status: "Verified",
    orgType: "NPO",
    createdAt: getRandomDate(startDate, endDate),
    updatedAt: getRandomDate(startDate, endDate),
    lastInteraction: getRandomDate(startDate, endDate),
    availableResources: "Community development, social services",
  },
  {
    id: createId(),
    name: "TechWave Solutions",
    status: "Pending",
    orgType: "Corporate",
    createdAt: getRandomDate(startDate, endDate),
    updatedAt: getRandomDate(startDate, endDate),
    lastInteraction: getRandomDate(startDate, endDate),
    availableResources: "IT consultancy, cloud services",
  },
  {
    id: createId(),
    name: "TravelLite Agency",
    status: "Unverified",
    orgType: "Sole Proprietorship",
    createdAt: getRandomDate(startDate, endDate),
    updatedAt: getRandomDate(startDate, endDate),
    lastInteraction: getRandomDate(startDate, endDate),
    availableResources: "Travel packages, tour guides",
  },
  {
    id: createId(),
    name: "FutureEnergy Solutions",
    status: "Verified",
    orgType: "Corporate",
    createdAt: getRandomDate(startDate, endDate),
    updatedAt: getRandomDate(startDate, endDate),
    lastInteraction: getRandomDate(startDate, endDate),
    availableResources: "Renewable energy projects, environmental consultancy",
  },
  {
    id: createId(),
    name: "FarmFresh Co-op",
    status: "Pending",
    orgType: "Cooperative",
    createdAt: getRandomDate(startDate, endDate),
    updatedAt: getRandomDate(startDate, endDate),
    lastInteraction: getRandomDate(startDate, endDate),
    availableResources: "Organic farming, local produce",
  },
  {
    id: createId(),
    name: "TradeMasters Inc.",
    status: "Verified",
    orgType: "Corporate",
    createdAt: getRandomDate(startDate, endDate),
    updatedAt: getRandomDate(startDate, endDate),
    lastInteraction: getRandomDate(startDate, endDate),
    availableResources: "International trade, logistics",
  },
  {
    id: createId(),
    name: "InnovaHealth Solutions",
    status: "Verified",
    orgType: "Limited Liability Company (LLC)",
    createdAt: getRandomDate(startDate, endDate),
    updatedAt: getRandomDate(startDate, endDate),
    lastInteraction: getRandomDate(startDate, endDate),
    availableResources: "Healthcare services, medical supplies",
  },
  {
    id: createId(),
    name: "SmartHomes Innovations",
    status: "Pending",
    orgType: "Corporate",
    createdAt: getRandomDate(startDate, endDate),
    updatedAt: getRandomDate(startDate, endDate),
    lastInteraction: getRandomDate(startDate, endDate),
    availableResources: "Smart home solutions, home automation",
  },
  {
    id: createId(),
    name: "GreenPlanet Solutions",
    status: "Unverified",
    orgType: "Limited Liability Company (LLC)",
    createdAt: getRandomDate(startDate, endDate),
    updatedAt: getRandomDate(startDate, endDate),
    lastInteraction: getRandomDate(startDate, endDate),
    availableResources: "Environmental consultancy, sustainable products",
  },
  {
    id: createId(),
    name: "TechSavvy Solutions",
    status: "Verified",
    orgType: "Corporate",
    createdAt: getRandomDate(startDate, endDate),
    updatedAt: getRandomDate(startDate, endDate),
    lastInteraction: getRandomDate(startDate, endDate),
    availableResources: "IT consultancy, custom software development",
  },
  {
    id: createId(),
    name: "WellnessPlus Center",
    status: "Pending",
    orgType: "Partnership",
    createdAt: getRandomDate(startDate, endDate),
    updatedAt: getRandomDate(startDate, endDate),
    lastInteraction: getRandomDate(startDate, endDate),
    availableResources: "Wellness programs, health consultancy",
  },
  {
    id: createId(),
    name: "UrbanEco Solutions",
    status: "Verified",
    orgType: "Corporate",
    createdAt: getRandomDate(startDate, endDate),
    updatedAt: getRandomDate(startDate, endDate),
    lastInteraction: getRandomDate(startDate, endDate),
    availableResources: "Urban planning, sustainable development",
  },
];

export default partnersSeed;

export async function seedDb() {
  await db.insert(partners).values(partnersSeed);
}
